services:
  - type: web
    name: discord-bot
    env: node
    region: frankfurt
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev && \
      npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
